### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by tdruez** [zapier/django-rest-hooks#46]
Django 2.0 is now available https://www.djangoproject.com/weblog/2017/dec/02/django-20-released/

`django-rest-hooks` cannot be used with Django 2.0 at the moment:

```
[...]
lib/python3.6/site-packages/rest_hooks/models.py", line 43, in AbstractHook
    user = models.ForeignKey(AUTH_USER_MODEL, related_name='%(class)ss')
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

From https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0:
> The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations.

A value need to be set for `on_delete` on the `user` ForeignKey of the AbstractHook 
 model: https://github.com/zapier/django-rest-hooks/blob/master/rest_hooks/models.py#L43

@avelis any input on what should be a safe default value? `CASCADE`?

**Comment by avelis** [comment]
@tdruez Yeah I'd say `CASCADE` is a safe one to have. I could see the case for `null` but would prefer to have webhooks cleanup if a User associated to them is deleted as well.

**Comment by tdruez** [comment]
@avelis PR https://github.com/zapier/django-rest-hooks/pull/47 ready for review.

**Comment by tdruez** [comment]
@avelis thanks for the merge! `master` works fine with Django 2.0 in my codebase.
Do you mind pushing a release on pypi?
Cheers!

**Comment by tdruez** [comment]
Hi @avelis, anything blocking a pypi release including the Django 2.0 compatibility that I could help with?

**Comment by avelis** [comment]
@tdruez https://github.com/zapier/django-rest-hooks/releases/tag/v1.5.0

**Comment by tdruez** [comment]
@avelis awesome, thanks 👍
